### PR TITLE
Updates to dreq_content

### PR DESCRIPTION
**Pull request by sol1105**
- Version parsing supports agreed pattern (1.0alpha, 1.0.0, ...)
- `get_versions(local=True)` replaced with `get_cached()`
- `get_versions`: added parameter `target='tags'` (can also be 'branches')
- `get_versions`: added fallback (parsing the regular github repo page) in case the request to the GitHub API fails 
- `retrieve` will update locally cached json files when remote json is from branch and not tag
- `_get_latest_version` now retrieves remote versions if not previously done
- added consolidation function and mapping table in `consolidate_export.py`
- supporting raw and release exports for branches and tags, respectively
- added `kwargs` for a few functions maybe required by developers
- suppressing pooch info output
- updated readme
- added tests

### CODE REVIEW

**Comment by sol1105** [comment]
Todo
- ~~assert access to github api is not required to retrieve versions~~
- ~~potentially find alternative to retrieve list of tags than the github api~~
- ~~add consolidation part (3-base-export to 1-base-export)~~ (more or less)
- ~~support retrieval of both, 3-base-export and 1-base-export files~~

**Comment by sol1105** [comment]
@JamesAnstey 
Regarding the naming of the Airtable exports, what do you think of naming them
- "dreq_raw_export.json" for the 3-base export (so keep that name)
- "dreq_consolidated[_export].json" for the 1-base export with other possibilities for "consolidated" to be eg. "version",  "release", "tagged", ...

I think "raw_export" still fits for the 3-base export and do not see the need to change it.

**Comment by sol1105** [comment]
@JamesAnstey The 3-base exports (so far) lack the following tables that are part of the one-base export: 
'Ranking', 'Priority Level', 'Glossary', 'Table Identifiers', 'Frequency', 'Modelling Realm', 'Data Request Themes'

**Comment by JamesAnstey** [comment]
> @JamesAnstey Regarding the naming of the Airtable exports, what do you think of naming them
> 
> * "dreq_raw_export.json" for the 3-base export (so keep that name)
> * "dreq_consolidated[_export].json" for the 1-base export with other possibilities for "consolidated" to be eg. "version",  "release", "tagged", ...
> 
> I think "raw_export" still fits for the 3-base export and do not see the need to change it.

@sol1105 Good point, it's not that important to change the name of the 3-base "working version" export. (Btw it's actually 4 bases now, but the 4th one is a base describing the schema and it hardly affects the overall size at all.) I agree let's keep it as `dreq_raw_export.json`. For the 1-base export, I think `dreq_release_export.json` is clearest, since the key point is that it contains the content of an official data request release. I'll use this as the name in the content repo that I'm about to update with the `v1.0beta` release base content.

**Comment by JamesAnstey** [comment]
> @JamesAnstey The 3-base exports (so far) lack the following tables that are part of the one-base export: 'Ranking', 'Priority Level', 'Glossary', 'Table Identifiers', 'Frequency', 'Modelling Realm', 'Data Request Themes'

Yes, the tables are not the same in the 3-base and 1-base exports. On my branch that has general python classes to represent the base tables, in this module:
https://github.com/CMIP-Data-Request/CMIP7_DReq_Software/blob/ja_class_test/sandbox/JA/dreq_query.py
I made two functions to transform an exported content dict into table objects:
```
def create_dreq_tables_for_request(content):
def create_dreq_tables_for_variables(content):
```
They attempt to handle differences between the "raw" export (4 bases) and "release" export (1 base) under the hood. Although similar I made them separate functions for simplicity and to help with separating bits involving the "request" part from the "variables" part of the data request, as @rigoudyg has done. I don't know if it's the best solution, it's what I arrived at so far. Because of the inconsistent tables, there are still differences that have to be handled downstream of this, for example [here for the Priority Level table](https://github.com/CMIP-Data-Request/CMIP7_DReq_Software/blob/487c453ee06e915e32f0c858c85be43940bcd7e7/sandbox/JA/check_plev_requests.py#L61).

Perhaps at the next TISG meeting it would be good to discuss whether these inconsistencies should be resolved in Airtable (by adjusting bases to be more consistent with the 1-base export) or in the software. Our priority is for the software to support the 1-base export since those are the official versions, but I think (hope) that supporting the 4-base working version will be helpful to thematic author teams as the software becomes more capable. Personally I find it really useful for the software to be able to use the working version export.

**Comment by sol1105** [comment]
@JamesAnstey I agree it can be handled in your code, but the idea was to set up a consolidation process in python that creates a 1:1 copy of the release export out of a raw export. And this is only possible if the tables that Beth is considering in Airtable to create her release base are actually present in the raw export as well.
I open an issue for this.

Apart from the missing tables, the `consolidate_export.py` has a mapping function that does the consolidation.

**Comment by sol1105** [comment]
@matthew-mizielinski There is now a fallback in case the GitHub API cannot be accessed, it would be great if you gave feedback if it works for you.

**Comment by matthew-mizielinski** [comment]
> @matthew-mizielinski There is now a fallback in case the GitHub API cannot be accessed, it would be great if you gave feedback if it works for you.

Thanks @sol1105, I'm getting clear exceptions now when there are issues

**Comment by sol1105** [comment]
As decided in the TISG meeting I will merge and open another PR regarding the consolidation part.

**Pull request merged**
